# Generated by Django 3.2.3 on 2021-06-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20210529_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='code_discount',
        ),
    ]
