# Generated by Django 3.2.3 on 2021-06-01 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20210601_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='kilometer',
            field=models.CharField(default='', max_length=30, verbose_name='Kilometer Details'),
        ),
        migrations.AddField(
            model_name='car',
            name='mode',
            field=models.CharField(default='rent', max_length=20),
        ),
        migrations.CreateModel(
            name='BookTaxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_from', models.CharField(max_length=30, verbose_name='From')),
                ('to_location', models.CharField(max_length=30, verbose_name='To')),
                ('date', models.DateTimeField(verbose_name='Date & Time')),
                ('status', models.BooleanField(default=True)),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
