# Generated by Django 3.2.3 on 2021-06-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20210601_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kilometer',
            field=models.CharField(default='', max_length=50, verbose_name='Kilometer Details'),
        ),
    ]
